//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wagenpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAR()
        {
            this.ONDERHOUD = new HashSet<ONDERHOUD>();
        }
    
        public string Kenteken { get; set; }
        public string Merk { get; set; }
        public string AutoType { get; set; }
        public int DealerNr { get; set; }
        public int InUse { get; set; }

        public virtual DEALER DEALER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ONDERHOUD> ONDERHOUD { get; set; }
    }
}
