//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wagenpark.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WagenparkDBEntities : DbContext
    {
        public WagenparkDBEntities()
            : base("name=WagenparkDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAR> CAR { get; set; }
        public virtual DbSet<DEALER> DEALER { get; set; }
        public virtual DbSet<ONDERHOUD> ONDERHOUD { get; set; }
        public virtual DbSet<WERKPLAATS> WERKPLAATS { get; set; }
    }
}
